ALTER TABLE users ADD COLUMN is_approved TINYINT(1) DEFAULT 0;

CREATE TABLE notifications_admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50),
  data TEXT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  read_flag TINYINT(1) DEFAULT 0
);

CREATE TABLE active_visitors (
  session_id VARCHAR(255) PRIMARY KEY,
  last_ping TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
